
```
try {
    // do something
    throw xxx;
} catch (ExceptionName e1) {
    // ...
} catch (ExceptionName e2) {
    // ...
} catch (...) {
    // ...
}
```

## 抛出异常

throw 语句的操作数可以是任意的表达式，表达式的结果的类型决定了抛出的异常的类型  

## 捕获异常

`catch` 能够捕获与其声明类型对应的抛出错误  

如果想让 `catch` 块能够处理 `try` 块抛出的任何类型的异常，则必须在异常声明的括号内使用省略号 `...`  

## 抛出数据与捕获类型对应表

| 抛出数据 | 捕获类型 |
| --- | --- |
| "msg" | `const char *` |
| 对象 | 类 |
